name: "Go example"
description: "Go example"
inputs:
  token:  # version
    description: 'Token'
    required: true
  pattern:
    description: 'Description'
    required: true
  org:
    description: 'Organization'
    required: true
outputs:
  allowedpatterns:
    description: "allowdpatterns"
    value: ${{ steps.addPattern.outputs.allowedPatterns }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
  - run: ls -l
    shell: bash
  - id: addPattern
    run: go run goexample.go ${{ inputs.token }} ${{ inputs.pattern }} ${{ inputs.org }}
    shell: bash
